package executor

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"

	"github.com/nemuri/nemuri/internal/agent"
	"github.com/nemuri/nemuri/internal/github"
	"github.com/nemuri/nemuri/internal/state"
)

func (e *Executor) executeCodeJob(ctx context.Context, job *state.Job, resp agent.AgentResponse, reviewResult *agent.ReviewLoopResult) (string, error) {
	if e.GitHub == nil {
		return "", fmt.Errorf("code generation requested but GitHub client is not configured")
	}
	if e.DefaultGHOwner == "" || resp.Repo == "" || len(resp.Files) == 0 {
		return "", fmt.Errorf("code response missing required fields (owner, repo, or files)")
	}

	branch := fmt.Sprintf("nemuri/%s", truncateJobID(job.JobID))
	slog.Info("creating code deliverable", "job_id", job.JobID, "owner", e.DefaultGHOwner, "repo", resp.Repo, "branch", branch, "files", len(resp.Files))

	defaultBranch, err := e.GitHub.GetDefaultBranch(ctx, e.DefaultGHOwner, resp.Repo)
	if err != nil {
		return "", fmt.Errorf("get default branch: %w", err)
	}
	if err := e.GitHub.CreateBranch(ctx, e.DefaultGHOwner, resp.Repo, defaultBranch, branch); err != nil {
		return "", fmt.Errorf("create branch: %w", err)
	}

	pr, err := e.commitAndCreatePR(ctx, job, resp, e.DefaultGHOwner, defaultBranch, branch)
	if err != nil {
		return "", err
	}

	message := buildPRNotificationMessage(pr.URL, resp.Title, resp.Description, resp.Files, reviewResult)

	threadID, err := e.createThreadAndNotify(ctx, job, message)
	if err != nil {
		return "", fmt.Errorf("notify Discord: %w", err)
	}
	return threadID, nil
}

func (e *Executor) executeNewRepoJob(ctx context.Context, job *state.Job, resp agent.AgentResponse, reviewResult *agent.ReviewLoopResult) (string, error) {
	if e.GitHub == nil {
		return "", fmt.Errorf("new repo requested but GitHub client is not configured")
	}
	if resp.Repo == "" || len(resp.Files) == 0 {
		return "", fmt.Errorf("new_repo response missing required fields (repo or files)")
	}

	slog.Info("creating new repository", "job_id", job.JobID, "repo", resp.Repo)

	repoResult, err := e.GitHub.CreateRepo(ctx, github.CreateRepoInput{
		Name:        resp.Repo,
		Description: resp.RepoDescription,
		Private:     true,
	})
	if err != nil {
		return "", fmt.Errorf("create repo: %w", err)
	}
	slog.Info("repository created", "job_id", job.JobID, "full_name", repoResult.FullName)

	parts := strings.SplitN(repoResult.FullName, "/", 2)
	if len(parts) != 2 {
		return "", fmt.Errorf("unexpected repo full_name format: %s", repoResult.FullName)
	}
	owner, repo := parts[0], parts[1]

	rollbackRepo := func(cause error) (string, error) {
		slog.Warn("rolling back repository creation", "owner", owner, "repo", repo, "cause", cause)
		if delErr := e.GitHub.DeleteRepo(ctx, owner, repo); delErr != nil {
			slog.Error("failed to delete repo during rollback", "error", delErr)
		}
		return "", cause
	}

	if err := e.GitHub.WaitForRepoReady(ctx, owner, repo, repoResult.DefaultBranch); err != nil {
		return rollbackRepo(fmt.Errorf("wait for repo ready: %w", err))
	}

	branch := fmt.Sprintf("nemuri/%s", truncateJobID(job.JobID))
	if err := e.GitHub.CreateBranch(ctx, owner, repo, repoResult.DefaultBranch, branch); err != nil {
		return rollbackRepo(fmt.Errorf("create branch: %w", err))
	}

	resp.Repo = repo

	pr, err := e.commitAndCreatePR(ctx, job, resp, owner, repoResult.DefaultBranch, branch)
	if err != nil {
		return rollbackRepo(err)
	}

	message := "リポジトリを作成しました: " + repoResult.HTMLURL + "\n" +
		buildPRNotificationMessage(pr.URL, resp.Title, resp.Description, resp.Files, reviewResult)

	threadID, err := e.createThreadAndNotify(ctx, job, message)
	if err != nil {
		return "", fmt.Errorf("notify Discord: %w", err)
	}
	return threadID, nil
}

func (e *Executor) commitAndCreatePR(ctx context.Context, job *state.Job, resp agent.AgentResponse, owner, baseBranch, branch string) (*github.PRResult, error) {
	files := make([]github.FileEntry, len(resp.Files))
	for i, f := range resp.Files {
		files[i] = github.FileEntry{
			Path:    f.Path,
			Content: []byte(f.Content),
		}
		resp.Files[i].Content = ""
	}

	commitMsg := fmt.Sprintf("feat: %s\n\nGenerated by Nemuri (job: %s)", resp.Title, job.JobID)
	if err := e.GitHub.CommitFiles(ctx, owner, resp.Repo, branch, commitMsg, files); err != nil {
		return nil, fmt.Errorf("commit files: %w", err)
	}

	// Save artifacts to S3 (best-effort)
	if e.Storage != nil {
		artifactData, err := json.Marshal(resp)
		if err != nil {
			slog.Warn("failed to marshal artifact", "error", err, "job_id", job.JobID)
		} else if err := e.Storage.UploadArtifact(ctx, job.JobID, "code_response.json", artifactData); err != nil {
			slog.Warn("failed to upload artifact to S3", "error", err, "job_id", job.JobID)
		}
	}

	pr, err := e.GitHub.CreatePR(ctx, github.PRInput{
		Owner:  owner,
		Repo:   resp.Repo,
		Base:   baseBranch,
		Branch: branch,
		Title:  resp.Title,
		Body:   fmt.Sprintf("%s\n\n---\nGenerated by Nemuri (job: `%s`)", resp.Description, job.JobID),
	})
	if err != nil {
		return nil, fmt.Errorf("create PR: %w", err)
	}
	slog.Info("PR created", "job_id", job.JobID, "pr_url", pr.URL, "pr_number", pr.Number)
	return pr, nil
}
